#!/usr/bin/env bash

export DAEMONIZED=1
source $SNAP/helper/functions

lprint "Connected wiht z2m!"
lprint "$(ls ${SNAP_DATA})"

SNAP_CONFIG="$(snapctl get --plug :store-dir z2mconfig)"

if [ -n "${SNAP_CONFIG}" ]; then
	lprint "${SNAP_CONFIG}"
	echo "${SNAP_CONFIG}" > "${SNAP_DATA}/.snap.config"
	if [ "$(snapctl get --plug :store-dir z2mserial)" -eq 1 ]; then
		lprint "Serial-port is enabled on Z2M, wont enable ${SNAP_NAME} automatically. Connect interface and enable ZUI with «sudo zwave-js-ui.enable"
		echo "disable" > "${SNAP_DATA}/.hook.install"
	else
		lprint "Tell install-hook to enable ZUI"
		echo "enable" > "${SNAP_DATA}/.hook.install"
	fi
else
	lprint "Do not have snap plug config"
fi


