#!/usr/bin/env bash

export DAEMONIZED=1
source $SNAP/helper/functions

SERVICE_FILE="${SNAP_DATA}/.install.hook.service"
lprint "Disconneting from Z2M, service = $(cat "${SERVICE_FILE}")"

if [ -s "${SERVICE_FILE}" ]; then
	if [ "$(cat "${SERVICE_FILE}")" == "enable" ]; then
		lprint "Enabling ${SNAP_NAME}: install.hook.service=$(cat "${SERVICE_FILE}")"
		snapctl start --enable "${SNAP_NAME}.${SNAP_NAME}"
	fi
	# Don't consider the «disable» term, as it should automatically disconnect;
	# Manually disconnect = start ZUI yourself
	rm "${SERVICE_FILE}"
fi
