#!/usr/bin/env bash

export DAEMONIZED=1
source $SNAP/helper/functions

set -e 

test_default_config

# The daemon is disabled by default after install; the user enables it explicitly
# with «${SNAP_NAME}.enable» (see «${SNAP_NAME}.help»).
lprint "Disabling ${SNAP_NAME} by default after install; enable it with «${SNAP_NAME}.enable»"
snapctl stop --disable "${SNAP_NAME}.${SNAP_NAME}"


