#!/usr/bin/env bash

source $SNAP/helper/functions

set -e 

# AS OF S0+n NETWORK KEY IS NOT USED ANYMORE
# SETTINGS_KEY=$(same_network_key "")
#
# if [ $? -eq 0 ]; then
#     SETTINGS_KEY=$(cat /dev/urandom | LC_ALL=C tr -dc '0-9A-F' | fold -w 32 | head -n 1)
# fi
#
# # Not needed anymore as of ZWAVEJS_EXTERNAL_CONFIG ?
# # ensure_zwavejs_config
#
# testnset_config "network.key" "${SETTINGS_KEY}"

settings_key=$(same_network_key "")
if [ $? -eq 0 ]; then
    settings_key=$(cat /dev/urandom | lc_all=c tr -dc '0-9a-f' | fold -w 32 | head -n 1)
fi
test_default_config

if [ -s "${SNAP_DATA}/.hook.install" ]; then
	if [ "$(cat "${SNAP_DATA}/.hook.install")" == "enable" ]; then
		logger "Enabling ${SNAP_NAME}: hook.install=$(cat "${SNAP_DATA}/.hook.install")"
		snapctl start --enable "${SNAP_NAME}.${SNAP_NAME}"
	else
		logger "Disabling ${SNAP_NAME}: hook.install=$(cat "${SNAP_DATA}/.hook.install")"
		snapctl stop --disable "${SNAP_NAME}.${SNAP_NAME}"
	fi
else
	logger "Disabling ${SNAP_NAME}: see command «${SNAP_NAME}.help»"
	snapctl stop --disable "${SNAP_NAME}.${SNAP_NAME}"
fi


