#!/usr/bin/env bash

source $SNAP/helper/functions

if [ -d "${SNAP_COMMON}/latest-device-config/config" ]; then
    logger "Restoring latest device config latest-device-config to ${ZWAVE_JS_CONF}"
    rsync -raz "${SNAP_COMMON}/latest-device-config/config" "${ZWAVE_JS_CONF}/.."
else
    ensure_zwavejs_config
fi

test_default_config
