#!/usr/bin/env bash

source $SNAP/helper/functions

# Not needed anymore as of ZWAVEJS_EXTERNAL_CONFIG?
# if [ -d "${SNAP_COMMON}/latest-device-config/config" ]; then
#     logger "Restoring latest device config latest-device-config to ${ZWAVE_JS_CONF}"
#     rsync -raz "${SNAP_COMMON}/latest-device-config/config" "${ZWAVE_JS_CONF}/.."
# else
#     ensure_zwavejs_config
# fi

test_default_config

# Update deviceConfigPriorityDir to match new revision
if [ -d "${SNAP_DATA}" ]; then
	PRIORITY_DIR=$(echo "$(sed -E "s#$(dirname ${SNAP_DATA})/(current|[0-9]+)#${SNAP_DATA}#g" <<< $(cat "${SNAP_DATA}/settings.json" | jq '.zwave.deviceConfigPriorityDir'))" | tr -d '"')
	if [ -d $(dirname "${PRIORITY_DIR}") ]; then
	    jq --arg deviceConfigPriorityDir ${PRIORITY_DIR} '.zwave.deviceConfigPriorityDir = $deviceConfigPriorityDir' $SNAP_DATA/settings.json > $SNAP_DATA/tmp.json
        if [ $? -eq 0 ]; then
            mv $SNAP_DATA/tmp.json $SNAP_DATA/settings.json
        fi
	fi
fi

# Update references to the external config directory
# Discussed with Al Calzone, lead dev of Zwavejs, can just be deleted and re-build
EXT_CONFIG_DIR_INDEX="$(find "${SNAP_DATA}" -path *.ext-config/devices/index.json -print0 -quit)"
rm -f "${EXT_CONFIG_DIR_INDEX}"
