#!/usr/bin/env bash

source $SNAP/helper/functions

# Not needed anymore as of ZWAVEJS_EXTERNAL_CONFIG?
# if [ -d "${SNAP_COMMON}/latest-device-config/config" ]; then
#     logger "Restoring latest device config latest-device-config to ${ZWAVE_JS_CONF}"
#     rsync -raz "${SNAP_COMMON}/latest-device-config/config" "${ZWAVE_JS_CONF}/.."
# else
#     ensure_zwavejs_config
# fi

test_default_config

# Update deviceConfigPriorityDir to match new revision
PRIORITY_DIR=$(echo "$(sed -E "s#$(dirname ${SNAP_DATA})/(current|[0-9]+)#${SNAP_DATA}#g" <<< $(cat "${SNAP_DATA}/settings.json" | jq '.zwave.deviceConfigPriorityDir'))" | tr -d '"')
if [ -d $(dirname "${PRIORITY_DIR}") ]; then
    jq --arg deviceConfigPriorityDir ${PRIORITY_DIR} '.zwave.deviceConfigPriorityDir = $deviceConfigPriorityDir' $SNAP_DATA/settings.json > $SNAP_DATA/tmp.json
    mv $SNAP_DATA/tmp.json $SNAP_DATA/settings.json
fi

# Update references to the external config directory
sed -iE "s#$(dirname ${SNAP_DATA})/(current|[0-9]+)#${SNAP_DATA}/#g" $ZWAVEJS_EXTERNAL_CONFIG/devices/index.json
