name: zwave-js-ui
base: core24
version: 'v9.12.0'
summary: Full-featured Z-Wave Control Panel and MQTT Gateway.
description: |
  Full-featured Z-Wave Control Panel and MQTT Gateway compatible with all known 500 and 
  700 series Z-Wave controller hardware adapters, Z-Wave JS runs on almost anything with 
  a little bit of computing power and a serial port.

  # Main features
  - Control Panel UI: Directly control your nodes and their values from the UI, including:
    - Nodes management: Add, remove, and configure all nodes in your Z-Wave network
    - Firmware updates: Update device firmware using manufacturer-supplied firmware files
    - Groups associations: Add, edit, and remove direct node associations
    - Z-Wave JS Exposed: Provides full-access to Z-Wave JS's APIs
  - Full-Featured Z-Wave to MQTT Gateway: Expose Z-Wave devices to an MQTT broker in a 
    fully configurable manner
  - Secured: Supports HTTPS and user authentication
  - Scene Management: Create scenes and trigger them by using MQTT apis (with timeout 
    support)
  - Debug Logs in the UI: See debug logs directly from the UI
  - Access Store Files in the UI: Access the files are stored in the persistent store 
    folder directly from the UI
  - Network Graph: Provides a beautiful map showing how nodes are communicating with the 
    controller
  - Supports the Official Home Assistant Integration: Can act as the backend driver for 
    the official Home Assistant integration, using the same driver and socket server as 
    the official addon
  - Supports Home Assistant Discovery via MQTT: In lieu of the official integation, can 
    be used to expose Z-Wave devices to Home Assistant via MQTT discovery.
  - Supported by Domoticz (beta 2021.1): Using MQTT Autodiscovery.
  - Automatic/Scheduled backups: Scheduled backup of NVM and store directory. It's also 
    possible to enable automatic backups of NVM before every node inclusion/exclusion/
    replace, this ensures to create a safe restore point before any operation that can 
    cause a network corruption.

  ## Additions with the snap
  - Command to read the log from the terminal independent of if you're logging to file or not
  - Plugs for the `code-server` snap, if you want a full-fledge editor experience for the «store-folder»

  # Auto-connections
  - `raw-usb`: To access USB devices, such as Z-wave controller dongles
  - `hardware-observe`: To observe your system for devices, to easily find them in the UI

  **Note:** None of these connections are necessary to run the app, so you can disconnect them as you like, but please note that it might
    change the experience within the software.

grade: stable
confinement: strict
license: MIT
assumes:
  - command-chain

# platforms:
#  amd64:
#  arm64:
#    build-on: [arm64, amd64]
#    build-for: arm64
#  amrhf:
#    build-on: amd64
#    build-for: armhf
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64
  - build-on: arm64
    build-for: armhf

apps:
  zwave-js-ui:
    daemon: simple
    restart-condition: always
    environment:
      STORE_DIR: $SNAP_DATA
      ZWAVEJS_EXTERNAL_CONFIG: $SNAP_DATA/.ext-config
      DAEMONIZED: 1
      npm_config_cache: /usr/local/share/.cache/npm
    command: bin/npm start 
    command-chain:
      - helper/env-wrapper
    plugs:
      - network
      - network-bind
      - raw-usb
      - serial-port
      - hardware-observe
      - log-observe
  exec:
    environment:
      STORE_DIR: $SNAP_DATA
      ZWAVEJS_EXTERNAL_CONFIG: $SNAP_DATA/.ext-config
    command: bin/npm start 
    command-chain:
      - helper/env-wrapper
    plugs:
      - network
      - network-bind
      - raw-usb
      - serial-port
      - hardware-observe
  help:
    command: helper/env-wrapper --help
  enable:
    command: bin/daemonize
  disable:
    command: bin/de-daemonize
  restart:
    command: bin/restart

layout: # Cache is set to (env) something outside the rw mount, to prevent storing it inside the store dir.
  /usr/local/share/.cache/npm:
    bind: $SNAP/.cache/npm
  #/usr/local/share/.yarn: ?? Do we need this? Leave until proper testing is OK
    #symlink: $SNAP/lib/node_modules

slots: # ZUI offers new config dir within data (e.g for code-server snap)
  store-dir:
    interface: content
    content: vscs-content
    write:
      - $SNAP_DATA

parts:
  zwave-js-ui:
    after: [nodejs, dependencies]
    plugin: dump
    source: https://github.com/zwave-js/zwave-js-ui.git
    #source-branch: "feat#2871"
    #source-tag: "v7.1.0"
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    build-packages:
      - gcc
      - build-essential
    build-environment:
      - LD_LIBRARY_PATH: "${LD_LIBRARY_PATH}:$(dirname $(find ${CRAFT_PART_NAME} -name libonig.so.2 -print0))"
      - PATH: "${PATH}:${CRAFT_PART_NAME}/bin"
    override-build: |
      set +x
      # Used when testing an unreleased version of Z-wavejs
      # sed -i 's/"zwave-js".*$/"zwave-js"\: "10.0.5-0-pr-4836-ed10b36"/g' ${CRAFT_PART_NAME}/package.json
      
      # Necessary for the remote build; sometimes.
      if [ -n "${http_proxy-}" ]; then
        npm config set proxy "${http_proxy}"
      fi
      if [ -n "${https_proxy-}" ]; then
        npm config set https-proxy "${https_proxy}"
      fi

      npm ci
      npm run build:server
      npm run build:ui
      # remove dev dependencies
      npm prune --omit=dev
      
      # Copy built version into install directory
      mkdir -p "${CRAFT_PART_NAME}/lib/" \
        && cp --archive --link --no-dereference "${CRAFT_PART_NAME}" \
          "${CRAFT_PART_NAME}/lib/zwave-js-ui"
    stage:
      - lib/zwave-js-ui/.git
      - lib/zwave-js-ui/dist
      - lib/zwave-js-ui/node_modules
      - lib/zwave-js-ui/server
      - lib/zwave-js-ui/snippets
      - lib/zwave-js-ui/package.json
      - lib/zwave-js-ui/LICENSE
      - lib/zwave-js-ui/README.md
  
  dependencies:
    plugin: nil
    stage-snaps:
      - jq
      - yq
    stage-packages:
      - git
      - udev
      - iproute2

  nodejs:
    plugin: dump
    source:
      - to amd64: https://nodejs.org/dist/v20.13.1/node-v20.13.1-linux-x64.tar.gz
      - to arm64: https://nodejs.org/dist/v20.13.1/node-v20.13.1-linux-arm64.tar.gz
      - to armhf: https://nodejs.org/dist/v20.13.1/node-v20.13.1-linux-armv7l.tar.gz
    stage-packages:
      - libatomic1
    organize:
      '*.md': nodejs/
      LICENSE: nodejs/
    prime:
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
      - -include
      - -share
      - lib/node_modules/npm
      - bin/npm
      - bin/node
      - -bin/npx
      - -bin/corepack
    override-stage: |
      corepack disable
      craftctl stage

  local:
    plugin: dump
    source: src/
    stage-packages:
      - uuid
    organize:
      hooks: snap/hooks
