name: zwave-js-ui
title: Zwave JS UI
base: core24
version: v11.6.1
summary: Full-featured Z-Wave Control Panel and MQTT Gateway.
description: | # markdown
  Full-featured Z-Wave Control Panel and MQTT Gateway compatible with all known 500 and 
  700 series Z-Wave controller hardware adapters, Z-Wave JS runs on almost anything with 
  a little bit of computing power and a serial port.

  # Main features
  - Control Panel UI: Directly control your nodes and their values from the UI, including:
    - Nodes management: Add, remove, and configure all nodes in your Z-Wave network
    - Firmware updates: Update device firmware using manufacturer-supplied firmware files
    - Groups associations: Add, edit, and remove direct node associations
    - Z-Wave JS Exposed: Provides full-access to Z-Wave JS's APIs
  - Full-Featured Z-Wave to MQTT Gateway: Expose Z-Wave devices to an MQTT broker in a 
    fully configurable manner
  - Secured: Supports HTTPS and user authentication
  - Scene Management: Create scenes and trigger them by using MQTT apis (with timeout 
    support)
  - Debug Logs in the UI: See debug logs directly from the UI
  - Access Store Files in the UI: Access the files are stored in the persistent store 
    folder directly from the UI
  - Network Graph: Provides a beautiful map showing how nodes are communicating with the 
    controller
  - Supports the Official Home Assistant Integration: Can act as the backend driver for 
    the official Home Assistant integration, using the same driver and socket server as 
    the official addon
  - Supports Home Assistant Discovery via MQTT: In lieu of the official integation, can 
    be used to expose Z-Wave devices to Home Assistant via MQTT discovery.
  - Supported by Domoticz (beta 2021.1): Using MQTT Autodiscovery.
  - Automatic/Scheduled backups: Scheduled backup of NVM and store directory. It's also 
    possible to enable automatic backups of NVM before every node inclusion/exclusion/
    replace, this ensures to create a safe restore point before any operation that can 
    cause a network corruption.

  ## Additions with the snap
  - Command to read the log from the terminal independent of if you're logging to file or not
  - Plugs for the `code-server` snap, if you want a full-fledge editor experience for the «store-folder»

  # Auto-connections
  - `raw-usb`: To access USB devices, such as Z-wave controller dongles
  - `hardware-observe`: To observe your system for devices, to easily find them in the UI

  **Note:** None of these connections are necessary to run the app, so you can disconnect them as you like, but please note that it might
    change the experience within the software.

grade: stable
confinement: strict
license: MIT

donation:
  - https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=69NA8SXXFBDBN&source=https://snapcraft.io/zwave-js-ui
  - https://github.com/sponsors/robertsLando
  - https://github.com/sponsors/AlCalzone
issues:
  - https://github.com/giaever-online-iot/zwave-js-ui/issues
source-code:
  - https://github.com/giaever-online-iot/zwave-js-ui
  - https://github.com/zwave-js/zwave-js-ui
  - https://github.com/zwave-js/zwave-js
website:
  - https://zwave-js.github.io/zwave-js-ui
  - https://zwave-js.github.io/zwave-js/
contact:
  - https://discord.com/users/809194474240344144

platforms:
  amd64:
  arm64:
  armhf:

apps:
  zwave-js-ui:
    daemon: simple
    restart-condition: always
    environment:
      STORE_DIR: $SNAP_DATA
      ZWAVEJS_EXTERNAL_CONFIG: $SNAP_DATA/.ext-config
      DAEMONIZED: 1
      npm_config_cache: /usr/local/share/.cache/npm
    command: lib/node_modules/zui-snap/node_modules/.bin/zwave-js-ui
    command-chain:
      - helper/env-wrapper
    plugs:
      - network
      - network-bind
      - raw-usb
      - serial-port
      - hardware-observe
      - log-observe
  exec:
    environment:
      STORE_DIR: $SNAP_DATA
      ZWAVEJS_EXTERNAL_CONFIG: $SNAP_DATA/.ext-config
      npm_config_cache: /usr/local/share/.cache/npm
    command: lib/node_modules/zui-snap/node_modules/.bin/zwave-js-ui
    command-chain:
      - helper/env-wrapper
    plugs:
      - network
      - network-bind
      - raw-usb
      - serial-port
      - hardware-observe
  help:
    command: helper/env-wrapper --help
  enable:
    command: bin/daemonize
  disable:
    command: bin/de-daemonize
  restart:
    command: bin/restart

layout: 
  # Cache is set to (env) something outside the rw mount, to prevent storing it inside the store dir.
  /usr/local/share/.cache/npm:
    bind: $SNAP/.cache/npm
  #/usr/local/share/.yarn: ?? Do we need this? Leave until proper testing is OK
    #symlink: $SNAP/lib/node_modules

slots: # ZUI offers new config dir within data (e.g for code-server snap)
  store-dir:
    interface: content
    content: vscs-content
    write:
      - $SNAP_DATA

parts:
  zwave-js-ui:
    after: [dependencies]
    build-environment:
      - DEBUG_BUILD: "false"
    build-snaps:
      - yq
    plugin: npm
    npm-include-node: true
    npm-node-version: 22.20.0
    source: src/node
    override-build: | # shell
      set -x
      ZUIV="${SNAPCRAFT_PROJECT_VERSION#v}" yq -i '.version=env(ZUIV),.dependencies.zwave-js-ui=env(ZUIV)' -o=j "${CRAFT_PART_BUILD}/package.json"
      #cat "${CRAFT_PART_BUILD}/package.json"

      craftctl default

      # ! add extra debugging
      if [ "${DEBUG_BUILD}" == true ]; then
        echo "DEBUG"
        echo "process.on(\"warning\", (warning) => { console.warn(\"Node.js warning: \" + warning.stack);});" >> "${CRAFT_PART_INSTALL}/lib/node_modules/zui-snap/node_modules/.bin/zwave-js-ui"
      fi

    stage-packages:
      - on armhf:
        - libatomic1
    stage:
      - -bin/corepack
      - -bin/npx
      - -lib/node_modules/corepack
      - -lib/node_modules/npx

  dependencies:
    plugin: nil
    stage-snaps:
      - yq
    stage-packages:
      - udev
      - iproute2

  local:
    after: [dependencies]
    plugin: dump
    source: src/
    stage-packages:
      - uuid
    organize:
      hooks: snap/hooks
