name: Create Snap Track

on:
  workflow_run:
    workflows: ["PR Build Snap"]
    #types:
    #  - completed
    workflow_dispatch:  # Add this for manual testing

jobs:
  create-track:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      snap: zwave-js-ui
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Snapcraft CLI
        run: |
          sudo snap install snapcraft --classic

      - name: Retrive current tracks, version etc
        id: tracks
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        run: |
          tracks="$(snapcraft list-tracks zwave-js-ui)"
          echo "all: ${tracks}"
          echo "all=$(echo "${tracks}" | awk 'NR > 1 && $1 ~ /^v/ {print "\""substr($1, 2)"\""}' | paste -sd, - | sed 's/.*/[&]/'| yq '.' -oj -I0)" >> $GITHUB_OUTPUT
          echo "default=$(V="$(echo "${tracks}" | grep default | cut -d' ' -f1)" && echo "${V#v}")" >> $GITHUB_OUTPUT
          echo "current=$(V="$(yq '.version' snap/snapcraft.yaml)" && echo "${V#v}")" >> $GITHUB_OUTPUT

      - name: Output test
        run: |
          echo "${{ steps.tracks.outputs.all }}"
          echo "${{ steps.tracks.outputs.all }}" | yq '.' -oj

          echo "Default: ${{ steps.tracks.outputs.default }}"
          echo "Current: ${{ steps.tracks.outputs.current }}"
